"use strict";

// Browser port of mnist_web/preprocessing.py (white-ink-crop20-mass-center28-v1).
// The resize step reproduces Pillow's 8-bit LANCZOS resampling (fixed-point,
// separable, horizontal pass then vertical pass) so the demo feeds the model
// exactly the pixels the Flask service would. tests/frontend.test.cjs checks
// this against fixtures generated by the Python implementation.
(function (root, factory) {
    const api = factory();
    if (typeof module === "object" && module.exports) module.exports = api;
    else root.MnistPreprocessing = api;
})(typeof self !== "undefined" ? self : this, function () {
    const IMAGE_SIZE = 28;
    const GLYPH_SIZE = 20;
    const INK_THRESHOLD = 20;
    const MIN_INK_PIXELS = 12;
    const PREPROCESSING_VERSION = "white-ink-crop20-mass-center28-v1";
    const PRECISION_BITS = 32 - 8 - 2;
    const LANCZOS_SUPPORT = 3;

    class EmptyDrawingError extends Error {}

    // Python's round(): halves go to the nearest even integer.
    function roundHalfEven(value) {
        const floor = Math.floor(value);
        const diff = value - floor;
        if (diff > 0.5) return floor + 1;
        if (diff < 0.5) return floor;
        return floor % 2 === 0 ? floor : floor + 1;
    }

    function sinc(x) {
        if (x === 0) return 1;
        const px = Math.PI * x;
        return Math.sin(px) / px;
    }

    function lanczos(x) {
        return x > -3 && x < 3 ? sinc(x) * sinc(x / 3) : 0;
    }

    // Mirrors precompute_coeffs() and normalize_coeffs_8bpc() in Pillow's Resample.c.
    function coefficients(inSize, outSize) {
        const scale = inSize / outSize;
        const filterScale = Math.max(scale, 1);
        const support = LANCZOS_SUPPORT * filterScale;
        const kernelSize = Math.ceil(support) * 2 + 1;
        const bounds = new Int32Array(outSize * 2);
        const weights = new Int32Array(outSize * kernelSize);
        const raw = new Float64Array(kernelSize);
        for (let xx = 0; xx < outSize; xx++) {
            const center = (xx + 0.5) * scale;
            const ss = 1 / filterScale;
            let xmin = Math.trunc(center - support + 0.5);
            if (xmin < 0) xmin = 0;
            let xmax = Math.trunc(center + support + 0.5);
            if (xmax > inSize) xmax = inSize;
            xmax -= xmin;
            let total = 0;
            let x = 0;
            for (; x < xmax; x++) {
                const w = lanczos((x + xmin - center + 0.5) * ss);
                raw[x] = w;
                total += w;
            }
            for (x = 0; x < xmax; x++) {
                const k = total !== 0 ? raw[x] / total : raw[x];
                weights[xx * kernelSize + x] = Math.trunc(
                    k * (1 << PRECISION_BITS) + (k < 0 ? -0.5 : 0.5),
                );
            }
            bounds[xx * 2] = xmin;
            bounds[xx * 2 + 1] = xmax;
        }
        return { bounds, weights, kernelSize };
    }

    function clip8(sum) {
        const value = sum >> PRECISION_BITS;
        return value < 0 ? 0 : value > 255 ? 255 : value;
    }

    // Pillow LANCZOS resize for a single-channel uint8 image.
    function resizeLanczos(pixels, width, height, outWidth, outHeight) {
        if (outWidth === width && outHeight === height) return Uint8Array.from(pixels);
        let current = pixels;
        let currentWidth = width;
        if (outWidth !== width) {
            const { bounds, weights, kernelSize } = coefficients(width, outWidth);
            const next = new Uint8Array(outWidth * height);
            for (let y = 0; y < height; y++) {
                for (let xx = 0; xx < outWidth; xx++) {
                    const xmin = bounds[xx * 2];
                    const count = bounds[xx * 2 + 1];
                    let sum = 1 << (PRECISION_BITS - 1);
                    for (let x = 0; x < count; x++) {
                        sum += current[y * width + x + xmin] * weights[xx * kernelSize + x];
                    }
                    next[y * outWidth + xx] = clip8(sum);
                }
            }
            current = next;
            currentWidth = outWidth;
        }
        if (outHeight !== height) {
            const { bounds, weights, kernelSize } = coefficients(height, outHeight);
            const next = new Uint8Array(currentWidth * outHeight);
            for (let yy = 0; yy < outHeight; yy++) {
                const ymin = bounds[yy * 2];
                const count = bounds[yy * 2 + 1];
                for (let x = 0; x < currentWidth; x++) {
                    let sum = 1 << (PRECISION_BITS - 1);
                    for (let y = 0; y < count; y++) {
                        sum += current[(y + ymin) * currentWidth + x] * weights[yy * kernelSize + y];
                    }
                    next[yy * currentWidth + x] = clip8(sum);
                }
            }
            current = next;
        }
        return current;
    }

    // Pillow's RGB -> L conversion (ITU-R 601-2 luma, 16-bit fixed point).
    function rgbaToGray(rgba, width, height) {
        const gray = new Uint8Array(width * height);
        for (let i = 0, p = 0; i < gray.length; i++, p += 4) {
            const alpha = rgba[p + 3];
            // Composite onto black, as the server does for transparent PNGs.
            const r = alpha === 255 ? rgba[p] : Math.round((rgba[p] * alpha) / 255);
            const g = alpha === 255 ? rgba[p + 1] : Math.round((rgba[p + 1] * alpha) / 255);
            const b = alpha === 255 ? rgba[p + 2] : Math.round((rgba[p + 2] * alpha) / 255);
            gray[i] = (r * 19595 + g * 38470 + b * 7471 + 0x8000) >> 16;
        }
        return gray;
    }

    function translateWithoutWrap(array, dx, dy) {
        const size = IMAGE_SIZE;
        const result = new Uint8Array(size * size);
        for (let y = 0; y < size; y++) {
            const sy = y - dy;
            if (sy < 0 || sy >= size) continue;
            for (let x = 0; x < size; x++) {
                const sx = x - dx;
                if (sx >= 0 && sx < size) result[y * size + x] = array[sy * size + sx];
            }
        }
        return result;
    }

    // Returns the centered 28x28 uint8 glyph that the model normalizes to [0, 1].
    function preprocessGray(gray, width, height) {
        let inkCount = 0;
        let top = height;
        let bottom = -1;
        let left = width;
        let right = -1;
        for (let y = 0; y < height; y++) {
            for (let x = 0; x < width; x++) {
                if (gray[y * width + x] > INK_THRESHOLD) {
                    inkCount++;
                    if (y < top) top = y;
                    if (y > bottom) bottom = y;
                    if (x < left) left = x;
                    if (x > right) right = x;
                }
            }
        }
        if (inkCount < MIN_INK_PIXELS) throw new EmptyDrawingError("Draw a digit first.");

        const cropWidth = right - left + 1;
        const cropHeight = bottom - top + 1;
        const cropped = new Uint8Array(cropWidth * cropHeight);
        for (let y = 0; y < cropHeight; y++) {
            for (let x = 0; x < cropWidth; x++) {
                cropped[y * cropWidth + x] = gray[(y + top) * width + x + left];
            }
        }
        const scale = Math.min(GLYPH_SIZE / cropWidth, GLYPH_SIZE / cropHeight);
        const resizedWidth = Math.max(1, roundHalfEven(cropWidth * scale));
        const resizedHeight = Math.max(1, roundHalfEven(cropHeight * scale));
        const resized = resizeLanczos(cropped, cropWidth, cropHeight, resizedWidth, resizedHeight);

        let centered = new Uint8Array(IMAGE_SIZE * IMAGE_SIZE);
        const offsetX = Math.floor((IMAGE_SIZE - resizedWidth) / 2);
        const offsetY = Math.floor((IMAGE_SIZE - resizedHeight) / 2);
        for (let y = 0; y < resizedHeight; y++) {
            for (let x = 0; x < resizedWidth; x++) {
                centered[(y + offsetY) * IMAGE_SIZE + x + offsetX] = resized[y * resizedWidth + x];
            }
        }

        let total = 0;
        let sumX = 0;
        let sumY = 0;
        for (let y = 0; y < IMAGE_SIZE; y++) {
            for (let x = 0; x < IMAGE_SIZE; x++) {
                const mass = centered[y * IMAGE_SIZE + x];
                total += mass;
                sumX += x * mass;
                sumY += y * mass;
            }
        }
        if (total <= 0) throw new EmptyDrawingError("The stroke is too small. Please draw again.");
        const target = (IMAGE_SIZE - 1) / 2;
        centered = translateWithoutWrap(
            centered,
            roundHalfEven(target - sumX / total),
            roundHalfEven(target - sumY / total),
        );
        return centered;
    }

    function toModelInput(glyph) {
        const input = new Float32Array(glyph.length);
        for (let i = 0; i < glyph.length; i++) input[i] = glyph[i] / 255;
        return input;
    }

    return {
        IMAGE_SIZE,
        PREPROCESSING_VERSION,
        EmptyDrawingError,
        roundHalfEven,
        resizeLanczos,
        rgbaToGray,
        preprocessGray,
        toModelInput,
    };
});
